apiVersion: v1
data:
  YAPI_PORT: "3001"
  YAPI_ACOUNT: admin@admin
  YAPI_DB_SERVER: 10.30.140.48
  YAPI_DB_NAME: yapi
  YAPI_DB_PORT: "27017"
  YAPI_DB_USER: yapipro
  YAPI_DB_PASS: "yapipro1024"
  YAPI_DB_AUTH: yapipro
kind: ConfigMap
metadata:
  name: yapi-config
  namespace: central
