apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yapi
  name: yapi
  namespace: central
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yapi
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: yapi
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: yapi-config
        image: 10.101.1.14:5000/yapi:latest
        imagePullPolicy: Always
        name: yapi
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        
      
