apiVersion: v1
kind: Service
metadata:
  labels:
    app: yapi
  name: yapi
  namespace: central
spec:
  ports:
  - name: http
    port: 3001
    protocol: TCP
    targetPort: 3001
    nodePort: 32700
  selector:
    app: yapi
  type: NodePort
